import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "@/lib/styles/globals.scss";
import Header from "@/app/header";

const mainFont = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Login",
	description: "Generated by create next app",
};

export default function LoginLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
			<Header needBackgroundHeader={false}/>
			{children}
		</>
	);
}
